### ISSUE TITLE
[BUG] CORS Issue in Firefox.

### ISSUE THREAD

**Issue by TFWol** [joaomgcd/TaskerWebUI#1]
Is was having issues trying to get the html working in Firefox because of CORS errors by running:

```python
import http.server
import socketserver

HOST = "localhost"
PORT = 8000

class CORSRequestHandler(http.server.SimpleHTTPRequestHandler):
    def end_headers(self):
        self.send_header('Access-Control-Allow-Origin', '*')
        self.send_header('Access-Control-Allow-Methods', 'GET')
        self.send_header('Cache-Control', 'no-store, no-cache, must-revalidate')
        return super(CORSRequestHandler, self).end_headers()

handler = CORSRequestHandler

with socketserver.TCPServer((HOST, PORT), handler) as httpd:
    print(f"Serving at http://{HOST}:{PORT}")
    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        print("\nServer stopped.")

```

Then I looked closer at the errors. It's actually the Tasker UI feature that's the culprit. It needs to set a CORS policy or it won't work for people with Firefox.

**Comment by joaomgcd** [comment]
Hi. Just to clarify, how are you running a python script in Firefox? Also, what is the relation of that python web server to Tasker's WebUI? Thanks in advance.

**Comment by TFWol** [comment]
Oh, I started by saving the html file to a folder on the PC and then opening it in Firefox where I got CORS errors.

I then tried to get around the issue by hosting the file as a website from the computer via python (so it wouldn't show as `file:///`), but still had the same error. Which confused me.

That's when I realized the reason is because the Tasker UI server itself needs to do the CORS fix.

**Comment by TFWol** [comment]
I figured it out. The html page is very unforgiving. The _exact_ format is `http://<phoneIP>:<port>/`
If you leave out that last slash, you get misleading errors.

Demo:

https://github.com/user-attachments/assets/dd2e2347-ce70-4d66-8355-9ab819882512
